server:
  port: 8091
  
spring:
  application:
    name: RATING-SERVICE
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=MS;encrypt=true;trustServerCertificate=true;
    username: sa
    password: Subhash_9657723827
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka